When cannot find info, let user type them (Working version)
thenaterhood/python-autocite pull request #3
Opened 2020-03-11 01:47 UTC by weathon

2020-03-13 23:49 UTC, thenaterhood requested changes
Very cool! This adds something of value with a lot of potential that can be built on. Getting this wired in a little deeper would be nice, but this is a great place to start so I'm happy to accept it.

I left some suggestions because I don't think the code comments add value, but otherwise looks good.

2020-03-13 23:49 UTC, thenaterhood commented on src/python_autocite/__main__.py
> +            # print(type(tmp))
```suggestion

```

2020-03-13 23:49 UTC, thenaterhood commented on src/python_autocite/__main__.py
> +            if("[[[AUTHORS]]]" in tmp): #可以优化速度
```suggestion
            if("[[[AUTHORS]]]" in tmp):
```

2020-03-13 23:49 UTC, thenaterhood commented on src/python_autocite/__main__.py
> +            if("[[[PUBLICATION DATE]]]" in tmp): #可以优化速度
```suggestion
            if("[[[PUBLICATION DATE]]]" in tmp):
```

2020-03-13 23:49 UTC, thenaterhood commented on src/python_autocite/__main__.py
> +            if("[[[TITLE]]]" in tmp): #可以优化速度 yong tmp 也不行
```suggestion
            if("[[[TITLE]]]" in tmp):
```

2020-03-13 23:49 UTC, thenaterhood commented on src/python_autocite/__main__.py
> +                tmp=tmp.replace("[[[TITLE]]]",input("Please enter the title manually: "))#Forget the "=" python
```suggestion
                tmp=tmp.replace("[[[TITLE]]]",input("Please enter the title manually: "))
```

2020-03-13 23:49 UTC, thenaterhood commented on src/python_autocite/__main__.py
> +            print(tmp)#missing
```suggestion
            print(tmp)
```

2020-03-16 16:59 UTC, weathon commented
I remove those comments

2020-03-18 01:53 UTC, thenaterhood commented
Thanks! Looks good!

2020-03-18 01:54 UTC, thenaterhood approved these changes

2020-03-18 01:54 UTC, merged